### ISSUE TITLE
Computation of Physical Variables from Oceanbench evaluation

### ISSUE THREAD

**Issue by nilsleh** [jejjohnson/ocn-tools#14]
@quentinf00 
continues [issue](https://github.com/jejjohnson/oceanbench/issues/71#issuecomment-2488158063) from oceanbench. This [gdrive folder](https://drive.google.com/drive/folders/1qzT-5VcrdV8gCkwBwJ2uR5HP4k4uv-0G?usp=sharing) contains the following:
- `test_predictions.nc`: this is the dataset resulting from calling `.reconstruct_from_batches()` given the pytorch model predictions
- `test_eval_ds.nc`: saves the eval ds based on the hydra config all following the [notebook](https://jejjohnson.github.io/oceanbench/content/getting_started/ocean_bench_4dvarnet.html#compute-the-task-metrics)
```python
cfg.outputs.summary.method = "4dvarnet"
cfg.results.outputs.eval.methods["4dvarnet"].inp = save_path
lb = hydra.utils.call(cfg.outputs)
eval_ds = lb.build_eval_ds()
```
- `test_maps_ds.nc`: is the dataset of calling `map_ds = lb.plots.build_ds.maps()`

If I try running the snippet from the [paper figure notebook](https://github.com/jejjohnson/oceanbench/blob/83ea5f35719f89bb4e66fb0c8c985fc309fa3922/notebooks/dev/neurips-paper/paper_fig_dc20a_maps.ipynb):

```python
import xarray as xr
from ocn_tools._src.geoprocessing import geostrophic as geocalc
def compute_variables(ds):
    ds = geocalc.streamfunction(ds, "ref")
    ds = geocalc.geostrophic_velocities(ds, variable="psi")
    ds = geocalc.kinetic_energy(ds, variables=["u", "v"])
    ds = geocalc.divergence(ds, variables=["u", "v"])
    ds = geocalc.coriolis_normalized(ds, "div")
    ds = geocalc.relative_vorticity(ds, variables=["u", "v"])
    ds = geocalc.coriolis_normalized(ds, "vort_r")
    ds = geocalc.strain_magnitude(ds, variables=["u", "v"])
    ds = geocalc.coriolis_normalized(ds, variable="strain")
    
    return ds


map_ds = xr.open_dataset("test_maps_ds.nc")

ds_with_vars = compute_variables(map_ds)
```

I get the error:
```
Traceback (most recent call last):
  File "/home/user/ocean_bench_exps/example_ocean_vars.py", line 20, in <module>
    ds_with_vars = compute_variables(map_ds)
  File "/home/user/ocean_bench_exps/example_ocean_vars.py", line 8, in compute_variables
    ds = geocalc.divergence(ds, variables=["u", "v"])
  File "/opt/conda/lib/python3.10/site-packages/ocn_tools/_src/geoprocessing/geostrophic.py", line 184, in divergence
    v=ds[variables[1]], u=ds[variables[0]], latitude=ds.lat, longitude=ds.lon
  File "/opt/conda/lib/python3.10/site-packages/xarray/core/dataset.py", line 1578, in __getitem__
    raise KeyError(
KeyError: "No variable named 'v'. Variables on the dataset include ['time', 'lat', 'lon', 'ke']"
```

slightly changing the script to avoid the above error:

```python
import xarray as xr
from ocn_tools._src.geoprocessing import geostrophic as geocalc

def compute_variables(ds):
    ds = geocalc.streamfunction(ds, "ref")
    ds_uv = geocalc.geostrophic_velocities(ds, variable="psi")

    ds_ke = geocalc.kinetic_energy(ds_uv, variables=["u", "v"])
    ds_div = geocalc.divergence(ds_uv, variables=["u", "v"])
    ds_rel_vort = geocalc.relative_vorticity(ds_uv, variables=["u", "v"])
    ds_strain = geocalc.strain_magnitude(ds_uv, variables=["u", "v"])

    ds_cor = geocalc.coriolis_normalized(ds_strain, variable="strain")
    ds_cor_norm_div = geocalc.coriolis_normalized(ds_div, "div")
    ds_cor_norm_vort = geocalc.coriolis_normalized(ds_rel_vort, "vort_r")
    
    return ds


map_ds = xr.open_dataset("test_maps_ds.nc")

ds_with_vars = compute_variables(map_ds)
```

I get:

```
Traceback (most recent call last):
  File "/home/user/ocean_bench_exps/example_ocean_vars.py", line 22, in <module>
    ds_with_vars = compute_variables(map_ds)
  File "/home/user/ocean_bench_exps/example_ocean_vars.py", line 10, in compute_variables
    ds_rel_vort = geocalc.relative_vorticity(ds_uv, variables=["u", "v"])
  File "/opt/conda/lib/python3.10/site-packages/ocn_tools/_src/geoprocessing/geostrophic.py", line 126, in relative_vorticity
    ds["vort_r"] = geocalc.vorticity(
  File "/opt/conda/lib/python3.10/site-packages/metpy/calc/tools.py", line 1179, in wrapper
    return func(*bound_args.args, **bound_args.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/metpy/xarray.py", line 1330, in wrapper
    result = func(*bound_args.args, **bound_args.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/metpy/units.py", line 332, in wrapper
    _check_units_inner_helper(func, sig, defaults, dims, *args, **kwargs)
  File "/opt/conda/lib/python3.10/site-packages/metpy/units.py", line 319, in _check_units_inner_helper
    raise ValueError(msg)
ValueError: This function changed in version(s) ['1.0']--double check that the function is being called properly.
`vorticity` given arguments with incorrect units: `u` requires "[speed]" but given "meter / second ** 2", `v` requires "[speed]" but given "meter / second ** 2"
```

Essentially I am looking for a way to compute these quantities, such that I can generate more custom map plots beyond the [visualize maps snippet](https://jejjohnson.github.io/oceanbench/content/getting_started/ocean_bench_4dvarnet.html#visualize-the-maps) in the oceanbench notebook. Thank you for any pointers.

**Comment by quentinf00** [comment]
Hi @nilsleh ,

I couldn't open the netcdf from you drive but I think I reproduced and found the issue:

The geostrophic velocities should be computed from the ssh variable (ref in you example)
you need to ensure that the ssh field has a meter unit (set in the netcdf variable attributes)

Here is a working snippet :
```python
import xarray as xr
import numpy as np
from ocn_tools._src.geoprocessing import geostrophic as geocalc

ds = xr.Dataset(
    dict(ref=(('lon', 'lat'), np.zeros((100, 100)), dict(units='m') )),               #note the unit
    coords=dict(lat=np.arange(10, 20, .1), lon=np.arange(10, 20, 0.1))
)

def compute_variables(ds):
    ds = ds.merge(geocalc.streamfunction(ds, "ref"))
    ds = ds.merge(geocalc.geostrophic_velocities(ds, variable="ref"))   # change of psi to ref
    ds = ds.merge(geocalc.kinetic_energy(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.divergence(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.coriolis_normalized(ds, "div"))
    ds = ds.merge(geocalc.relative_vorticity(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.coriolis_normalized(ds, "vort_r"))
    ds = ds.merge(geocalc.strain_magnitude(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.coriolis_normalized(ds, variable="strain"))
    
    return ds

compute_variables(ds)
```

**Comment by nilsleh** [comment]
Hi @quentinf00, 

Thank you for your reply. Apologies, I uploaded the .nc file again, it must have been corrupted, but should work now.

Given your pointer of requiring meter units, I saw that there is a function in ocn_tools: `latlon_deg2m` so I was wondering whether that could do the trick for the actual data:

```python
import xarray as xr
import numpy as np
from ocn_tools._src.geoprocessing import geostrophic as geocalc
from ocn_tools._src.geoprocessing.spatial import latlon_deg2m

def compute_variables(ds):
    """Compute geophysical variables from a dataset.
    
    ds: xarray.Dataset with "ref" and "study" variable and dimensions [time, lat, lon]
    """
    ds = latlon_deg2m(ds).isel(time=0)
    ds = ds.merge(geocalc.streamfunction(ds, "ref"))
    ds = ds.merge(geocalc.geostrophic_velocities(ds, variable="ref"))   # change of psi to ref
    ds = ds.merge(geocalc.kinetic_energy(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.divergence(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.coriolis_normalized(ds, "div"))
    ds = ds.merge(geocalc.relative_vorticity(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.coriolis_normalized(ds, "vort_r"))
    ds = ds.merge(geocalc.strain_magnitude(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.coriolis_normalized(ds, variable="strain"))
    
    return ds

map_ds = xr.open_dataset("test_maps_ds.nc")
out = compute_variables(map_ds)

```

But then I get the error:
```
Traceback (most recent call last):

    ds = ds.merge(geocalc.streamfunction(ds, "ref"))
  File "/opt/conda/lib/python3.10/site-packages/ocn_tools/_src/geoprocessing/geostrophic.py", line 36, in streamfunction
    f0 = geocalc.coriolis_parameter(latitude=np.deg2rad(ssh.lat.pint.dequantify())).mean()
  File "/opt/conda/lib/python3.10/site-packages/metpy/xarray.py", line 1330, in wrapper
    result = func(*bound_args.args, **bound_args.kwargs)
  File "/opt/conda/lib/python3.10/site-packages/metpy/calc/basic.py", line 629, in coriolis_parameter
    latitude = _check_radians(latitude, max_radians=np.pi / 2)
  File "/opt/conda/lib/python3.10/site-packages/metpy/calc/basic.py", line 1317, in _check_radians
    value = value.to('radians').m
  File "/opt/conda/lib/python3.10/site-packages/pint/facets/plain/quantity.py", line 536, in to
    magnitude = self._convert_magnitude_not_inplace(other, *contexts, **ctx_kwargs)
  File "/opt/conda/lib/python3.10/site-packages/pint/facets/plain/quantity.py", line 480, in _convert_magnitude_not_inplace
    return self._REGISTRY.convert(self._magnitude, self._units, other)
  File "/opt/conda/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 1041, in convert
    return self._convert(value, src, dst, inplace)
  File "/opt/conda/lib/python3.10/site-packages/pint/facets/context/registry.py", line 405, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/opt/conda/lib/python3.10/site-packages/pint/facets/nonmultiplicative/registry.py", line 259, in _convert
    return super()._convert(value, src, dst, inplace)
  File "/opt/conda/lib/python3.10/site-packages/pint/facets/plain/registry.py", line 1076, in _convert
    raise factor
pint.errors.DimensionalityError: Cannot convert from 'meter' ([length]) to 'radian' (dimensionless)
```

**Comment by nilsleh** [comment]
Update:

This does work:

```python
import xarray as xr
import numpy as np
from ocn_tools._src.geoprocessing import geostrophic as geocalc

def compute_variables(ds):
    """Compute geophysical variables from a dataset.
    
    ds: xarray.Dataset with "ref" and "study" variable and dimensions [time, lat, lon]
    """

    for var_name in ds.data_vars:
        ds[var_name].attrs['units'] = 'm'

    ds = ds.merge(geocalc.streamfunction(ds, "ref"))
    ds = ds.merge(geocalc.geostrophic_velocities(ds, variable="ref"))   # change of psi to ref
    ds = ds.merge(geocalc.kinetic_energy(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.divergence(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.coriolis_normalized(ds, "div"), compat="override")
    ds = ds.merge(geocalc.relative_vorticity(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.coriolis_normalized(ds, "vort_r"), compat="override")
    ds = ds.merge(geocalc.strain_magnitude(ds, variables=["u", "v"]))
    ds = ds.merge(geocalc.coriolis_normalized(ds, variable="strain"), compat="override")
    
    return ds

map_ds = xr.open_dataset("test_maps_ds.nc")
out = compute_variables(map_ds)
```
So actually, lat/lon only need to have "meter" as units, although the actual values are lat/lon degree values?!

**Comment by quentinf00** [comment]
H @nilsleh ,
Sorry if it was not clear, the ssh variable need to have meter as units and the lat lon variable are in degrees. there are helper functions to do this in `ocn_tools._src.geoprocessing.validation`
you can do the following which should prepare everything right:
```python
ds = ocn_tools._src.geoprocessing.validation.validate_ssh(ds, variable='ref) # set units=meter
ds = ocn_tools._src.geoprocessing.validation.validate_latlon(ds) # set units=deg north/east + convert lon range in -180, 180 and lat range in -90, 90
```

**Comment by nilsleh** [comment]
Ah cool thanks for the clarification. Sorry for my misunderstanding. that was really helpful! :)
